# Generated by Django 4.2.8 on 2023-12-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile2.jpg', upload_to='profile_pics'),
        ),
    ]
